name: Merge and PR into 2021.2
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'mps/2021.1'
jobs:
  merge-and-PR-in-2021-1:
    # only trigger if it was actually merged
    if: github.event.pull_request.merged == true
    
    runs-on: ubuntu-latest
    steps:

      # checkout the target branch
      - name: Checkout mps/2021.1
        uses: actions/checkout@v3
        with:
          ref: 'mps/2021.2'
          fetch-depth: 0
            
      # actually merge from the previous branch
      - run: |
         git config user.name 'github-actions[bot]'
         git config user.email 'github-actions[bot]@users.noreply.github.com'
         git merge origin/mps/2021.1 --

         # stip title of previous version suffix
         NEW_TITLE=${{ github.event.pull_request.title }}
         NEW_TITLE=${NEW_TITLE// (2020.3 -> 2021.1)}
         echo NEW_TITLE=$NEW_TITLE >> $GITHUB_ENV
      
      # create a PR based on the merge
      - name: Create PR for MPS 2021.2
        uses: peter-evans/create-pull-request@v5
        with:
          #branch: 'autoPR/mps/2021.1/${{ github.head_ref }}'
          branch: 'mergePR/mps/2021.2'
          commit-message: Merge mps/2021.1 into mps/2021.2
          title: ${{ env.TOXENV }} (2021.1 -> 2021.2)
          body: |
            This is an automatic PR which merges changes from `mps/2021.1` to `mps/2021.2`
            
            [Original PR content on `mps/2021.1`:](${{ github.event.pull_request._links.html.href }})
            
            > ${{ github.event.pull_request.body }}
